#  _
# |_)|    _ _ |._|_|_
# |  ||_|| (_||| | | |
#
# Welcome to Pluralith!
# https://www.pluralith.com
#
# This is your Pluralith config file
# Learn more about it at https://docs.pluralith.com/config

project_id: 0
# config:
#   senitive_attrs:
#     - "attribute_name"
#     - "attribute_name"
#   vars:
#     - "NAME=VALUE"
#     - "NAME=VALUE"
#   var_files:
#     - "./var_file.tfvars"
#     - "./var_file.tfvars"
#   cost_usage_file: "./usage_file.yml"

# export:
#   title: ""
#   author: ""
#   version: ""

